services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3307:3306"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    container_name: new-mailer
    image: axllent/mailpit
    ports:
      - "8026:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
