<?php

namespace App\Repository;

use App\Entity\Event;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Event::class);
    }

    public function findFutures(\DateTime $max = null)
    {
        $qb = $this->createQueryBuilder('e');

        $qb
            ->where("e.date > :now")
            ->setParameter('now', new \Datetime('now'));

        if ($max) {
            $qb
                ->andWhere('e.date < :max')
                ->setParameter('max', $max);
        }

        $qb->orderBy("e.id", 'ASC');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
