<?php

namespace App\Repository;

use App\Entity\HelloassoPayment;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * HelloassoPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelloassoPaymentRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, HelloassoPayment::class);
    }

    public function findOrphan()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('p')
            ->from($this->getEntityName(), 'p')
            ->where('p.registration IS NULL');

        return $qb->getQuery()->getResult();
    }
}
