<?php

namespace App\Repository;

use App\Entity\PeriodPosition;
use App\Entity\Beneficiary;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * PeriodRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodPositionRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, PeriodPosition::class);
    }

    /**
     * @param int $beneficiary
     *
     * @return array
     */
    public function findByBeneficiary($beneficiary)
    {
        $qb = $this->createQueryBuilder('pp');
        $qb->where('pp.shifter = :shifter')
            ->setParameter('shifter', $beneficiary)
            ->leftJoin('pp.period', 'p')
            ->addOrderBy('p.dayOfWeek', 'ASC')
            ->addOrderBy('p.start', 'ASC');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param array $beneficiaries
     *
     * @return array
     */
    public function findByBeneficiaries($beneficiaries)
    {
        $qb = $this->createQueryBuilder('pp');
        $qb->where('pp.shifter IN (:shiftersId)')
            ->setParameter('shiftersId', array_map(function(Beneficiary $beneficiary) {
                return $beneficiary->getId();
            }, $beneficiaries->toArray()))
            ->leftJoin('pp.period', 'p')
            ->addOrderBy('p.dayOfWeek', 'ASC')
            ->addOrderBy('p.start', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
